apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: feedparser
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
    matchExpressions:
      - { key: tier, operator: In, values: [backend] }
  template:
    metadata:
      labels:
        app: feedparser
        tier: backend
    spec:
      containers:
      - name: mongodb
        image: asia.gcr.io/feedparser-198104/feedparser/mongodb:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "256m"
            memory: "500Mi"
