apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: feedparser
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - { key: tier, operator: In, values: [frontend] }
  template:
    metadata:
      labels:
        app: feedparser
        tier: frontend
    spec:
      volumes:
        - name: assets
      containers:
      - name: nginx
        image: asia.gcr.io/feedparser-198104/feedparser/nginx
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /app/assets
            name: assets
      - name: node-ssr
        image: asia.gcr.io/feedparser-198104/feedparser/node_ssr
        lifecycle:
          postStart:
            exec:
              command:
                - "/app/sonken/docker/install.sh"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8081
        volumeMounts:
          - mountPath: /app/assets
            name: assets
        env:
          - name: TOP_URL
            value: "http://35.200.100.73"
          - name: API_PATH
            value: "/api"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: NODE_ENV
            value: "staging"
      - name: node-api
        image: asia.gcr.io/feedparser-198104/feedparser/node_api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8082
        env:
          - name: TOP_URL
            value: "http://35.200.100.73"
          - name: API_PATH
            value: "/api"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: NODE_ENV
            value: "staging"
