apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: feedparser-tls
  namespace: default
spec:
  secretName: feedparser-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: alpha-one-rss.jp
  dnsNames:
    - feedparser.alpha-one-rss.jp
  acme:
    config:
    - dns01:
        provider: feedparser-dns
      domains:
      - alpha-one-rss.jp
      - feedparser.alpha-one-rss.jp
