apiVersion: batch/v1
kind: Job
metadata:
  name: worker
  labels:
    app: feedparser
    tier: worker
spec:
  template:
    metadata:
      labels:
        app: feedparser
        tier: worker
    spec:
      volumes:
      - name: assets
      restartPolicy: Never
      containers:
      - name: node-job
        image: asia.gcr.io/feedparser-198104/feedparser/node_job
        command: ["/app/sonken/docker/install.sh"]
        resources:
          requests:
            cpu: 256m
            memory: 128Mi
        volumeMounts:
          - mountPath: /app/assets/
            name: assets
