apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: feedparser
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: feedparser
    tier: backend
  ports:
  - name: mongomdb
    protocol: TCP
    port: 27017
    targetPort: 27017
