apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: feedparser
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
    matchExpressions:
      - { key: tier, operator: In, values: [backend] }
  template:
    metadata:
      labels:
        app: feedparser
        tier: backend
    spec:
      containers:
        - name: mongodb
          image: asia.gcr.io/feedparser-198104/feedparser/mongodb:latest
          ports:
          - containerPort: 27017
          env:
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password
          resources:
            requests:
              cpu: "256m"
              memory: "500Mi"
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4
