apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker
  labels:
    app: feedparser
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: worker
    matchExpressions:
      - { key: tier, operator: In, values: [worker] }
  template:
    metadata:
      labels:
        app: feedparser
        tier: worker
    spec:
      containers:
      - name: node-job
        image: asia.gcr.io/feedparser-198104/feedparser/node_job:latest
        resources:
          requests:
            cpu: 320m
            memory: 720Mi
