apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: feedparser
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - { key: tier, operator: In, values: [frontend] }
  template:
    metadata:
      labels:
        app: feedparser
        tier: frontend
    spec:
      volumes:
        - name: assets
      containers:
      - name: nginx
        image: asia.gcr.io/feedparser-217913/feedparser/nginx:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /app/assets
            name: assets
      - name: node-ssr
        image: asia.gcr.io/feedparser-217913/feedparser/node_ssr:latest
        resources:
          requests:
            cpu: 384m
            memory: 1024Mi
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - /app/sonken/docker/staging/install.sh
        ports:
          - containerPort: 8081
        volumeMounts:
          - mountPath: /app/assets
            name: assets
        env:
          - name: NODE_ENV
            value: "staging"
          - name: API_URL
            value: "http://35.227.255.168/api"
          - name: ASSET_URL
            value: "http://35.227.255.168/assets"
          - name: APP_NAME
            value: "SellerSearch!"
      - name: node-api
        image: asia.gcr.io/feedparser-217913/feedparser/node_api:latest
        resources:
          requests:
            cpu: 256m
            memory: 1440Mi
        env:
          - name: NODE_OPTIONS
            value: "--max_old_space_size=2048"
        ports:
          - containerPort: 8082
