apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: img-worker
  labels:
    app: feedparser
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: worker
    matchExpressions:
      - { key: tier, operator: In, values: [worker] }
  template:
    metadata:
      labels:
        app: feedparser
        tier: worker
    spec:
      containers:
      - name: node-img
        image: asia.gcr.io/feedparser-217913/feedparser/node_img:latest
        resources:
          requests:
            cpu: 64m
            memory: 256Mi
        env:
          - name: WORKER_NAME
            value: "img-worker"
