apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: itm-worker
  labels:
    app: feedparser
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: worker
    matchExpressions:
      - { key: tier, operator: In, values: [worker] }
  template:
    metadata:
      labels:
        app: feedparser
        tier: worker
    spec:
      containers:
      - name: node-itm
        image: asia.gcr.io/feedparser-217913/feedparser/node_itm:latest
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
